spring.application.name=task-manager

# SERVER
server.port=${PORT:8080}

# DATABASE - hardcoded Railway internal values
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jackson.serialization.fail-on-empty-beans=false

# JWT
jwt.secret=${JWT_SECRET:mySuperSecretKeyForJwtTokenRailway12345678!!}
jwt.expiration=86400000